In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
#2d array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
#Array Properties
a.shape # size
a.size  #Total elements
a.dtype #Datatype
a.ndim #Dimensions

2

In [17]:
np.eye(3) #Identity matrix
np.arange(1,10,2)
np.full((2,2),5)
np.ones((1,2))
np.zeros((2,2))
np.linspace(1,1,5)

array([1., 1., 1., 1., 1.])

In [19]:
#Convert type:
arr = np.array([1, 2, 3], dtype=float)

arr.astype(int)

array([1, 2, 3])

In [ ]:
#Indexing:
a=np.array([10,20,30,40,50,60])
a[1]
a[:4]
a[3:]
a[2:4]
a[-1]

array([30, 40])

In [ ]:
#For 2D:
b=np.arr([[10,20,30],[40,50,60]])