In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#2d array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
#Array Properties
a.shape # size
a.size  #Total elements
a.dtype #Datatype
a.ndim #Dimensions

2

In [5]:
np.eye(3) #Identity matrix
np.arange(1,10,2)
np.full((2,2),5)
np.ones((1,2))
np.zeros((2,2))
np.linspace(1,1,5)

array([1., 1., 1., 1., 1.])

In [6]:
#Convert type:
arr = np.array([1, 2, 3], dtype=float)

arr.astype(int)

array([1, 2, 3])

In [7]:
#Indexing:
a=np.array([10,20,30,40,50,60])
a[1]
a[:4]
a[3:]
a[2:4]
a[-1]

np.int64(60)

In [11]:
b = np.array([[1,2,3],[4,5,6]])

b[0,1]      # row 0, col 1
b[:,1]      # all rows, col 1
b[1,:]      # row 1


array([4, 5, 6])

In [13]:
#Boolean indexing:
a = np.array([10, 20, 30, 40])

a[a > 20]
a[(a > 10) & (a < 40)]


array([20, 30])

In [14]:
#Math operations
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b
a * b
a ** 2


array([1, 4, 9])

In [ ]:
#Aggrigation functions:
a.sum()
a.mean()
a.min()
a.max()
a.std()

np.float64(0.816496580927726)

In [23]:
#Reshaping
a=np.arange(1,7)
a.reshape(2,3)
a.flatten()
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [24]:
#Splitting
np.split(a, 3)


[array([1, 2]), array([3, 4]), array([5, 6])]

In [25]:
#Set random:
np.random.rand(3,3)
np.random.randn(3,3)
np.random.randint(1, 100, size=(3,3))


array([[ 4,  2, 83],
       [47, 67, 75],
       [78, 58, 39]], dtype=int32)

In [30]:
#searching and sorting
np.sort(a)
np.argsort(a)
np.where(a>2)

(array([2, 3, 4, 5]),)

In [31]:
#linear algebra:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

np.dot(A, B)
np.linalg.det(A)
np.linalg.inv(A)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
#Handling missing values
a = np.array([1, 2, np.nan, 4])

np.isnan(a)
np.nanmean(a)
np.nan_to_num(a)


array([1., 2., 0., 4.])

In [34]:
# Python list
sum([i*i for i in range(1000000)])

# NumPy
arr = np.arange(1000000)
(arr ** 2).sum()


np.int64(333332833333500000)